name: tiser
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip

  # Utilities
  - numpy=1.26.*
  - pandas=2.1.*
  - scikit-learn=1.3.*
  - tqdm
  - protobuf>=3.20,<5
  - sentencepiece
  - sacremoses  

  - pip:
      # PyTorch stack
      - torch>=2.6
      - torchvision
      - torchaudio

      # HF stack
      - transformers>=4.39.0
      - datasets>=2.16.1
      - accelerate>=0.27.0
      - peft>=0.10.0
      - trl>=0.8.0
      - wandb>=0.16.0
      - bitsandbytes
      - tokenizers>=0.15.0
      - regex
      
      # Other
      - sentence-transformers>=2.5.0
      - langdetect 
      
     
